# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('lattes', models.URLField(blank=True, null=True, verbose_name='CV')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'photo/', verbose_name='Photo')),
                ('coordination', models.BooleanField(default=False, verbose_name='Coordination')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
